import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Terms() {
  return (
    <div className="container mx-auto py-12 px-6 max-w-4xl">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Terms of Service</CardTitle>
          <p className="text-muted-foreground">Effective Date: December 2025</p>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <h3>1. Acceptance of Terms</h3>
          <p>
            By accessing or using Ahsan AI Hub, you agree to be bound by these Terms of Service. 
            If you do not agree, please do not use the platform.
          </p>

          <h3>2. Description of Service</h3>
          <p>
            Ahsan AI Hub provides AI-powered tools for content generation, chat, and coding 
            assistance. The service is provided "as is" and for free.
          </p>

          <h3>3. User Responsibilities</h3>
          <p>
            You are responsible for your use of the service and any content you generate. 
            You agree not to use the service for any illegal or harmful activities, including 
            generating hate speech, harassment, or malicious code.
          </p>

          <h3>4. Intellectual Property</h3>
          <p>
            The platform design, branding, and original code are the property of Ahsan Ali. 
            Content generated by the AI is yours to use, subject to the underlying AI provider's 
            terms.
          </p>

          <h3>5. Limitation of Liability</h3>
          <p>
            Ahsan AI Hub and its creator shall not be liable for any direct, indirect, incidental, 
            or consequential damages resulting from the use or inability to use the service.
          </p>

          <h3>6. Modifications to Service</h3>
          <p>
            We reserve the right to modify or discontinue the service at any time without notice. 
            As a free platform, we do not guarantee 100% uptime.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
